### ISSUE TITLE
harvesting error 

### ISSUE THREAD

**Issue by daimajia** [ragulin/face-recognition-server#5]
[E 140101 23:45:19 websocket:306] Uncaught exception in /harvesting
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 303, in wrapper
        return callback(_args, *_kwargs)
      File "server.py", line 55, in on_message
        self.process(image)
      File "server.py", line 94, in process
        result = opencv.Image(label=label).persist(cv_image)
      File "/root/School/Face/face-recognition-server-master/opencv.py", line 159, in persist
        cropped = to_grayscale(crop_faces(cv_image, faces))
      File "/root/School/Face/face-recognition-server-master/opencv.py", line 41, in crop_faces
        return img[y:y+h,x:x+w]
      File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 512, in **getattr**
        raise AttributeError(name)
    AttributeError: **getitem**

**Comment by daimajia** [comment]
when try to saving the first image, trigger this error.
