### ISSUE TITLE
Resize error

### ISSUE THREAD

**Issue by petaoctet** [ragulin/face-recognition-server#6]
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /usr/local/opencv/modules/imgproc/src/imgwarp.cpp, line 1824
Traceback (most recent call last):
  File "server.py", line 121, in <module>
    main()
  File "server.py", line 114, in main
    opencv.train()
  File "/home/petaoctet/Desktop/facerec/opencv.py", line 86, in train
    images, labels = load_images_from_db()
  File "/home/petaoctet/Desktop/facerec/opencv.py", line 78, in load_images_from_db
    cv_image = cv2.resize(cv_image, (100,100))
cv2.error: /usr/local/opencv/modules/imgproc/src/imgwarp.cpp:1824: error: (-215) ssize.area() > 0 in function resize

**Comment by pmalik13** [comment]
In image table of your data/images.db , there are entries for image paths which do not exist on disk . Remove those entries from image table and this error will go away .
I hope it helps .

**Comment by ramal321** [comment]
can you be more specfic please .. whr is the image table and data/images.db
